gaussian:
    theory: "APFD"
    light_basis_set: "6-31G*"
    heavy_basis_set: "LANL2DZ"
    generic_basis_set: "genecp"
    max_light_atomic_number: 36

slurm:
    wall_time: "23:59:00"
    atoms_per_processor: 6
    max_processors: 20
    ram_per_processor: 2

mongoDB:
    host: "128.112.123.54"
    port: 27017
    user: "autoqchem"
    password: "dftworks"