openbabel:
    gen3D_option: "best"

gaussian:
    theory: "APFD" # other option used recently is B3LYP
    light_basis_set: "6-31G*"
    heavy_basis_set: "LANL2DZ"
    generic_basis_set: "genecp"
    max_light_atomic_number: 36
    max_num_conformers: 30
    conformer_RMSD_threshold: 0.01 # in Angstroms
    conformer_weight_threshold: 0.00001
    min_dist_for_salts: 2 # in Angstroms

slurm:
    work_dir: "C:/Users/AndrzejZuranski/tmp/qchem/gaussian"
    wall_time: "23:59:00"
    atoms_per_processor: 6
    max_processors: 20
    ram_per_processor: 2

mongoDB:
    #host: "localhost"
    host: "128.112.123.54"
    port: 27017
    user: "autoqchem"
    password: "dftworks"